require "minitest/autorun"
require "minitest/rg"
require "sinatra/activerecord"
require_relative "../app/models/show.rb"
require_relative "../app/models/artist.rb"
require_relative "../app/models/art_piece.rb"
